#!/usr/bin/python
import subprocess
import sys

# Populate these options if you want to set specific options for the printer. E.g. duplexing installed, etc.
printerOptions = { "InputSlot":"Tray1", "EFPrintSize":"A3", "EFDuplex":"TopTop", "EFSpineBurnishing":"Auto", "EFFold":"CollateHalfFold", "EFTrimmer":"True", "EFStapler":"Stitch", "EFXerox_Light_Prod_Finisher":"LightProd_EU", "EFTrimmerOpt":"True", "EFGAFeaturesOpt":"GA2",  }

cmd = [ '/usr/sbin/lpadmin', '-x', 'A4Booklet' ]
proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
(lpadminxOut, lpadminxErr) = proc.communicate()

# Install the printer
cmd = [ '/usr/sbin/lpadmin',
        '-p', 'A4Booklet',
        '-L', '2nd Floor',
        '-D', 'A4Booklet',
        '-v', 'lpd://192.168.10.103/A4Booklet',
        '-P', "/Library/Printers/PPDs/Contents/Resources/en.lproj/Xerox Color EX 550-560",
        '-E',
        '-o', 'printer-is-shared=false',
        '-o', 'printer-error-policy=abort-job' ]

for option in printerOptions.keys():
    cmd.append("-o")
    cmd.append(str(option) + "=" +  str(printerOptions[option]))

proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
(lpadminOut, lpadminErr) = proc.communicate()

if lpadminErr:
    print "Error: %s" % lpadminErr
    sys.exit(1)
print "Results: %s" % lpadminOut
sys.exit(0)
